### ISSUE TITLE
When setting state in `onTabChange` the indicator isn't smooth

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#130]
When you change tabs and have some code that sets some state in `onTabChange` the Indicator movement isn't smooth. Please see video. 

[simulator8.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/5977995/simulator8.mov.zip)

This can be avoided by memoizing the tabs, e.g 

```js
const MemoizedTabs = useMemo(
    () => (
      <Tabs.Container
        lazy
        onTabChange={onTabChange}
        ref={pageRef}
        TabBarComponent={_renderTabBar}
      >
        .
        .
        .
      </Tabs.Container>
    ),
    [],
  );
```

And rendering just. 

```
{MemoizedTabs}
```

It may be a good idea to make a note of this in the Readme somewhere?

**Comment by andreialecu** [comment]
This should be fixed by #131, but please confirm.

**Comment by alexpchin** [comment]
I'm still seeing that the indicator isn't as smooth unless you use `useMemo`?

**Comment by andreialecu** [comment]
When I tested it on my simulator (M1 Mac Mini) I wasn't really able to notice the jumping. It was still extremely smooth. That's likely because the emulator and the CPU architecture are both `arm64` so there are no bottlenecks. It basically all runs native.

I mainly had to confirm this issue via some logging I added.

Did you verify if this occurs on a real device?

**Comment by andreialecu** [comment]
I added memoization just in case, released as `rc9`
