### ISSUE TITLE
FlatList. with numColumns not working on Android

### ISSUE THREAD

**Issue by hirbod** [PedroBern/react-native-collapsible-tab-view#250]
Hi,

I started working on the Android version of my app and just realized that my Tabs are empty, while perfectly filled on iOS.
Something is wrong with FlatList + `numColumns` with this library on Android. My content is underneath the header. When I remove numColumns, my content appears.

I played around a bit and it looks like I have to manually pass a marginTop of HEADERHEIGHT + TABBARHEIGHT to FlatList's `contentContainerStyle` to make my content visible on android. This breaks for iOS though.

For now, I can workaround the issue with some Platform checks, but I would kindly ask to support numColumns on Android as well.

**Comment by hirbod** [comment]
Unfortunately, I figured that this workaround does not work once the header is collapsed and you swipe between tabs...

**Comment by hirbod** [comment]
@andreialecu any chance you could have a look at this one here?

**Comment by hirbod** [comment]
@andreialecu this issue has been solved with v5. Thanks

**Comment by hirbod** [comment]
Fixed with v5, thanks!

**Comment by omotoshogyro** [comment]
This issue still persists in V6, I currently have a Flatlist with 3 columns I noticed the lists are not showing on Android but it showing on ios, I tried the hack above by applying marginTop and my lists start showing
