### ISSUE TITLE
Scroll position not synced properly when adding dynamic tabs and not using `lazy` mode

### ISSUE THREAD

**Issue by nkrmr** [PedroBern/react-native-collapsible-tab-view#259]
Hello when i scroll on top of my header each tab appear with a blank space.
I used : 
react-native-collapsible-tab-view : 4.5.2
react-native-reanimated : 2.8.0
react-native-tab-view : 3.1.1

https://user-images.githubusercontent.com/686395/167453214-4ee6ef71-f020-4b17-b340-584f7476ac3f.MP4

Can you help me

**Comment by niyasmhdth** [comment]
Having the same issue on android, but iOS is working fine. Any solution?

**Comment by andreialecu** [comment]
I'd suggest trying the v5 release candidate. Things have been rewritten there. See the PR on it for instructions.

**Comment by tom-richtr** [comment]
> I'd suggest trying the v5 release candidate. Things have been rewritten there. See the PR on it for instructions.

I have tried the latest v5 RC. The behavior is better, but the problem still occurs when header is collapsed and tab is changed. If the header is visible again then it continues to work as expected.

**Comment by andreialecu** [comment]
Need more info. iOS or Android? A recording of the issue will also help.

**Comment by tom-richtr** [comment]
I tested it on android with version 5.0.0-rc.7.
The first shorter video shows the problem when the header is collapsed and then tab is changed. You can see the empty space for the header which is however not shown.
The second video shows the similar case, but firstly we moved to the second tab, then the header is collapsed and then we swiped back and the problem with empty header space occured again. If the header is then expanded again then it starts to work further without any problems on any tab.

https://user-images.githubusercontent.com/54364588/169469577-96c436ab-18d0-46ab-bd57-7417ef1ddaa3.mp4

https://user-images.githubusercontent.com/54364588/169469601-3385796f-0974-40b0-83db-e3bbfcb56a7e.mp4

**Comment by andreialecu** [comment]
Can't seem to reproduce this in either my own apps or in the example app that is part of this library.

If you could isolate it that would be great.

https://user-images.githubusercontent.com/697707/169490079-38c0821e-b219-4aad-baca-b56676aaf880.mov

**Comment by tom-richtr** [comment]
It looks like the problem occurs if the tabs are generated dynamically. If we render tabs container just when we have all tabs ready then it works fine but if we add tabs dynamically then it happens what you can see in the videos.

**Comment by andreialecu** [comment]
@tom-richtr indeed this seems to be an issue when not using `lazy` tabs. I can reproduce it in the example app if I remove the `lazy` prop.

As a workaround, if it is feasible for you, try adding `lazy` to your `Tabs.Container`.

**Comment by tom-richtr** [comment]
We already use lazy mode and the issue is right there. I think the problem occurs with dynamic tabs loaded after initial rendering.

**Comment by aeminkyr** [comment]
I was having the same issue and it fixed after I updated to [5.0.0-rc.10] version thanks @andreialecu  :)

**Comment by Hartaithan** [comment]
same issue on 5.0.0-rc.13 version. whether lazy is used or not. any way to fix it?

**Comment by Hartaithan** [comment]
Any news? @andreialecu

**Comment by crzycoder** [comment]
@andreialecu I'm also facing same issue with Tab.container is lazy. Without lazy props its working fine.

**Comment by DSKonstantin** [comment]
Any updates?

**Comment by dincozdemir** [comment]
The problem happens when there is a `minHeaderHeight`

**Comment by andreialecu** [comment]
This should be fixed in latest versions. Try 6.1.2, closing for now, but feel free to let me know if it needs to be reopened.

**Comment by metinaltinbas** [comment]
@andreialecu still having the problem using 6.1.3

**Comment by miladdev85** [comment]
No matter lazy or header height I have this issue. It works on first render when I use lazy, but after switching tabs back and forth, the blank header problem is back...

**Comment by liveforownhappiness** [comment]
any updates?
6.2.1 has this issue in android

**Comment by hjun555** [comment]
still problem. scroll offset doesnt sync when there are multiple scrollview tabs..

**Comment by AbdoHema2016** [comment]
Here is a workaround to reset the scroll offset to the top on changing tabs that worked for me, would be great if someone can work out a better formula as I was on a tight schedule
 ```
  const tabScrollRef = useRef(null);
  const focusedTab = useFocusedTab();
  const scrollY = useCurrentTabScrollY();
  const scrollScreen = () => {
      if (scrollY.value > TABS_HEADER_HEIGHT) {
        tabScrollRef?.current?.scrollTo({ animated: false, y: -50 }); 
        return;
      }
      if (scrollY.value === 0) {
        tabScrollRef?.current?.scrollTo({ animated: false, y: -PROFILE_HEADER_HEIGHT });
        return;
      }
      if (scrollY.value < TABS_HEADER_HEIGHT) {
        tabScrollRef?.current?.scrollTo({ animated: false, y: -scrollY.value * 0.2 });
      }
    };
    useEffect(() => {
      if (tabScrollRef && focusedTab === 'currentTabName') {
        scrollScreen();
      }
    }, [focusedTab]);
    
    <Tabs.ScrollView
        ref={tabScrollRef}
     ></Tabs.ScrollView>
  
```
  ps
  if u r using flatlist it would be 
`tabScrollRef?.current?.scrollToOffset({ animated: false, offset: -scrollY.value * 0.2 });`
  and u can add the style `minHeight: undefined,` on the contentContainerStyle if u r having a footer that needs to be aligned with screen footer

**Comment by VictorioMolina** [comment]
+1

**Comment by andreialecu** [comment]
I believe this may have been fixed in 7.0.1 and beyond. Please ping to reopen this issue if it still exists.

**Comment by camiloparrado** [comment]
> Creo que esto se puede haber solucionado en la versión 7.0.1 y posteriores. Si el problema persiste, haz clic en ping para volver a abrirlo.

The problem still persists on Android with "react-native-collapsible-tab-view": "^8.0.0", is there any solution?

**Comment by mcalc001** [comment]
We are experiencing this on android: 
```
"react-native-collapsible-tab-view": "^8.0.0",
 "react-native-reanimated": "^3.15.1",
```

**Comment by gottfriedaniel** [comment]
Hello @andreialecu
Issue still persists on Android:
```
"react-native-collapsible-tab-view": "^8.0.1",
"react-native-pager-view": "^6.7.0",
"react-native-reanimated": "^3.16.4",
```

**Comment by vikramsingh-greytip** [comment]
@andreialecu The issue still exists. @nkrmr Please reopen this.
